column_name_mapping = {
    'Patient ID': 'patientID',
    'Patientkontakt ID': 'patientContactID',
    'Patient alder på kontaktstart tidspunkt': 'patientAgeAtContactStart',
    'Kontakt startdato': 'contactStartDate',
    'Kontakt slutdato': 'contactEndDate',
    'Kontakttype': 'contactType',
    'Indlæggelsesmåde': 'appointmentUrgency',
    'Patientkontakttype': 'patientContactType',
    'Aktionsdiagnosekode': 'primaryDiagnosisCode',
    'Bidiagnosekode': 'secondaryDiagnosisCode',
    'Behandlingsansvarlig Afdeling': 'responsibleDepartment',
    'Kontakt varighed (timer)': 'contactDurationHours',
    'Procedure-kode': 'procedureCode',
    'Procedure-tillægskoder': 'procedureSupplementaryCodes',
    'Procedure udført': 'procedurePerformed',
    'Behandlingskontakt ID': 'treatmentContactID',
    'Besøgstype': 'visitType',
    'Patient køn': 'patientGender',
    'Patient civilstand': 'patientMaritalStatus',
    'Patient oprettet på Min SP (J/N)': 'patientRegisteredInMySP',
    'Patient land': 'patientCountry',
    'Patient region': 'patientRegion',
    'Patient postnummer': 'patientPostalCode',
    'Patient kommune': 'patientMunicipality'
}
